[tox]
envlist =
    py{311,312}-django{42,52}
    lint
isolated_build = True

[testenv]
deps =
    -e .[test]
    -e ./tutor-plugin
    django42: Django>=4.2,<5.0
    django52: Django>=5.2,<5.3
commands =
    pytest -v --cov --cov-fail-under=85

[testenv:lint]
skip_install = True
deps =
    ruff>=0.6
commands =
    ruff check .
    ruff format --check .
