# Generated by Django 5.2.15 on 2026-06-04 14:27

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_inventory", "0002_coursetag_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursetag",
            options={
                "ordering": ("key", "value"),
                "verbose_name": "course tag",
                "verbose_name_plural": "course tags",
            },
        ),
        migrations.AlterModelOptions(
            name="savedview",
            options={
                "ordering": ("name",),
                "verbose_name": "saved view",
                "verbose_name_plural": "saved views",
            },
        ),
        migrations.AlterField(
            model_name="coursetag",
            name="course_id",
            field=opaque_keys.edx.django.models.CourseKeyField(
                db_index=True, max_length=255, verbose_name="course id"
            ),
        ),
        migrations.AlterField(
            model_name="coursetag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="coursetag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="coursetag",
            name="key",
            field=models.CharField(db_index=True, max_length=64, verbose_name="key"),
        ),
        migrations.AlterField(
            model_name="coursetag",
            name="value",
            field=models.CharField(db_index=True, max_length=128, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="filters_json",
            field=models.JSONField(default=dict, verbose_name="filters"),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="name",
            field=models.CharField(max_length=128, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_inventory_saved_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="shared",
            field=models.BooleanField(default=False, verbose_name="shared"),
        ),
        migrations.AlterField(
            model_name="savedview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
